### PR TITLE
Fixes Issue #185

### PR DESCRIPTION
**Pull request by JoseExposito**
Have a look to https://github.com/Keyang/node-csvtojson/issues/185 for explanation

### CODE REVIEW

**Comment by jjperezaguinaga** [comment]
Same here, this solves issue #185

**Comment by serenanubi** [comment]
Thanks for working on this solution! 💯

**Comment by JoseExposito** [comment]
All tests passing now 😃

**Comment by Keyang** [comment]
Sorry for the delay..Thanks for this solution.
I will push 1.1.8 containing this to npm soon.

**Pull request merged**
