### PR TITLE
strip BOM from input data

### PR DESCRIPTION
**Pull request by mhassan1**
The Byte Order Mark (BOM) is sometimes included in CSV files. In that case, this library will output:

`[ { '﻿"name"': 'joe', age: '20' },  { '﻿"name"': 'sam', age: '30' } ]`

Notice the "name" header actually contains double quotes. This is because the parser sees the BOM before the header and thinks it belongs in the first column header name. Try any file with a BOM in it and you will see. For someone to use this library, they would have to remove the BOM manually (or with some other library) before using this, which seems unnecessary to me, since the BOM is found in many CSV files without the user knowing it.

This PR strips out the BOM from every piece of data that goes through the transform stream. The only risk with this is that parsing speed slows down as a result. If that is the case, you could consider only trying to strip the BOM from the first piece of data in the file, or some other way.

### CODE REVIEW

**Comment by Keyang** [comment]
`preProcessRaw` may be override by developers who want to add `preProcess` hook.

Probably need to remove BOM somewhere else.

Could you please tell me when the BOM could appear in a file? at the beginning only or anywhere?

~Keyang

**Comment by mhassan1** [comment]
Oh, I didn't realize that. The BOM can only appear at the beginning of the
file. Where would be a better place for this?

**Comment by Keyang** [comment]
I think you can put it here if it only appears at the beginning.
https://github.com/Keyang/node-csvtojson/blob/master/libs/core/Converter.js#L86-L91

This chunk of code will only run for first chunk of data. But you probably need move line 92 to the beginning of the function in case the incoming data encoding is not utf8.

~Keyang

**Comment by Keyang** [comment]
Thanks

**Pull request merged**
